apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /nfsshare/pv11
    server: nfs.ocp3.local
  persistentVolumeReclaimPolicy: Recycle
