apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv10
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /nfsshare/pv10
    server: nfs.ocp3.local
  persistentVolumeReclaimPolicy: Recycle
