# Playbook for updating hosts as not configured by cloud-init
# Gary Crowe -  Principal Consultant 28/01/2021
#
# version: 1.0 - GC. First stab
#
- name: Update hosts file for master
  lineinfile:
    path: /etc/hosts
    line: '{{ masterip }} {{ master }}'

- name: Update hosts file for worker1
  lineinfile:
    path: /etc/hosts
    line: '{{ worker1ip }} {{ worker1 }}'

- name: Update hosts file for worker2
  lineinfile:
    path: /etc/hosts
    line: '{{ worker2ip }} {{ worker2 }}'
