# Configures master node 
# Gary Crowe, Principal consultant.  Computacenter

#- name: "Configure Master | Checking for root ssh public key"
#  stat: path=/root/.ssh/id_rsa.pub
#  register: a2

#- name: "Configure Master | generate key pair"
#  shell: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ''
#  when: a2.stat.exists is not defined or not a2.stat.exists

- name: Copy over private key so master can ssh to workers
  copy:
    src: /home/pi/.ssh/id_rsa
    dest: /root/.ssh/id_rsa
    owner: root
    group: root
    mode: '0600'

- name: "Configure Master | Install htpasswd"
  yum: state=installed name=httpd-tools

- name: "Configure Oshift hosts file | Origin ansible template creation"
  template:
    src: templates/origin_okd.j2
    dest: /etc/ansible/hosts
  tags:
    - "origin"

- name: "Configure Master | Install script for Centos"
  template:
    src: templates/install_okd.j2
    dest: /root/install_ocp.bash
    owner: root
    mode: 0500
  tags:
    - "origin"

- name: "Configure Master | Pull ansible-openshift 3.11 repo"
  command: /usr/bin/git clone https://github.com/openshift/openshift-ansible.git
  become: yes
  become_user: root
  args:
    chdir: /root
    creates: /root/openshift-ansible

# Add hostname in master file and remove 127.0.0.1 entry: https://bugzilla.redhat.com/show_bug.cgi?id=1655214
# 127.0.0.1 slave1.okd.local slave1
#
- name: Remove loopback entry
  lineinfile:
    path: /etc/hosts
    state: absent
    regexp: '^127\.0\.0\.1 {{master}} {{masterip}} {{ master | regex_replace('^(.*)\.*$', '\\1') }}'

- name: Update hosts file for master
  lineinfile:
    path: /etc/hosts
    line: '{{ masterip }} {{ master }}'

- name: Update hosts file for worker1
  lineinfile:
    path: /etc/hosts
    line: '{{ worker1ip }} {{ worker1 }}'

- name: Update hosts file for worker2
  lineinfile:
    path: /etc/hosts
    line: '{{ worker2ip }} {{ worker2 }}'
